config/routes.rb
Rails.application.routes.draw do
  
  get '/', to: 'index#home'
  
  resources :gossips
  
  resources :users 
  
  resources :cities
  
  resources :gossips do 
    resources :comments
  end

  resources :gossips do 
    resources :likes
  end


  get '/login'     => 'sessions#new'
	
	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'
	
	# delete action to log out:
	delete '/logout' => 'sessions#destroy'  

    get 'welcome/:first_name', to: 'welcome#show'
    #Route contact
    get '/contact', to: 'index#contact'
  
    #Route team
    get '/team', to: 'index#team'
  
  
  
end

app/models/user.rb
class User < ApplicationRecord
   has_many :gossips
   belongs_to :city
   has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
   has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
   has_many :comments
   has_secure_password
   validates :password, presence: true, length: { minimum: 6 }

   def self.get_user_id(id)
      return User.all[id.to_i - 1]
   end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   def index 
      @users = User.all
   end
   
   def show 
      @user = User.get_user_id(params[:id])
   end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      
      # store all emails in lowercase to avoid duplicates and case-sensitive login errors:
      @user.email.downcase!
      
      if @user.save
        # If user saves in the db successfully:
        flash[:notice] = "Account created successfully!"
        redirect_to '/login'
      else
        # If user fails model validation - probably a bad password or duplicate email:
        flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
        render :new
      end
    end
  
  private
  
    def user_params
      # strong parameters - whitelist of allowed fields #=> permit(:name, :email, ...)
      # that can be submitted by a form to the user model #=> require(:user)
      params.require(:user).permit(:first_name, :last_name, :email, :description, :city_id, :password, :password_confirmation)
    end
    

end
  

app/views/users/new.html.erb
<div class="card text-center mb-3">
  <div class="card-body">

<h1>Sign Up</h1>
<div class="container">
    <%= form_for @user do |f| %>
      <div class="row justify-content-center align-self-center mx-5">  
      <div class="col-3">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, options = {style:"height:30px;width:300px"} %>
      </div>
      </div>

      <div class="row justify-content-center align-self-center mx-5">  
      <div class="col-3">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, options = {style:"height:30px;width:300px"} %>
      </div>
      </div>

      <div class="row justify-content-center align-self-center mx-5">  
      <div class="col-3">
        <%= f.label :email %>
        <%= f.text_field :email, options = {style:"height:30px;width:300px"} %>
      </div>
      </div>

      <div class="row justify-content-center align-self-center mx-5">
      <div class="col-3">
        <%= f.label :description %>
        <%= f.text_field :description, options = {style:"height:30px;width:300px"} %>
      </div>
      </div>

      <div class="row justify-content-center align-self-center mx-5">
      <div class="col-3">
      <%= f.label :age %>
      <%= f.text_field :age, options = {style:"height:30px;width:300px"} %>
      </div>
      </div>

    <div class="row justify-content-center align-self-center mx-5"> 
    <div class="col-3">
    <%= f.label :city_id %>
    <%= f.text_field :city_id, options = {style:"height:30px;width:300px"} %>
    </div>
    </div>

    <div class="row justify-content-center align-self-center mx-5"> 
    <div class="col-3">
        <%= f.label :password %>
        <%= f.password_field :password, options = {style:"height:30px;width:300px"} %>
    </div>
    </div>

    <div class="row justify-content-center align-self-center mx-5"> 
    <div class="col-3">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, options = {style:"height:30px;width:300px"} %>
    </div>
    </div>

    <div class="row justify-content-center align-self-center mx-5"> 
    <div class="col-3">
        <%= f.submit "Sign up!" %>
      </div>
      </div>
    <% end %>

</div>
</div>
</div>

app/views/users/show.html.erb
<div class="card">
   <div class="card-header font-weight-bold">
   <img src="https://source.unsplash.com/200x200/?portrait?sig=<%=rand(1..50)%>" 
                     alt="avatar" class="rounded-circle img-fluid" style="width: 150px;"> 
   </div>
   <div class="card-body">                
      <h4 class="card-title"> Prenom : <%=@user.first_name%></h4>
      <div class="card-text">
      <p> Nom : <%=@user.last_name%></p>
      <p> Age : <%=@user.age%></p>
      <p> Description : <%=@user.description%></p>
      <p> Email : <%=@user.email%></p>
      <p> City : <%=@user.city.name%></p>
      <button type="button" class="btn btn-info"><%= link_to "Ville", city_path(@user.city) %> </button>
      </div>
   </div>  
</div>