config/routes.rb
Rails.application.routes.draw do
  
  get '/', to: 'index#home'
  
  resources :gossips
  
  resources :users 
  
  resources :cities
  
  resources :gossips do 
    resources :comments
  end

  resources :gossips do 
    resources :likes
  end


  get '/login'     => 'sessions#new'
	
	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'
	
	# delete action to log out:
	delete '/logout' => 'sessions#destroy'  

    get 'welcome/:first_name', to: 'welcome#show'
    #Route contact
    get '/contact', to: 'index#contact'
  
    #Route team
    get '/team', to: 'index#team'
  
  
  
end

app/models/gossip.rb
class Gossip < ApplicationRecord
   validates :title, length: {minimum: 3, maximum: 50}, presence: true
   validates :content, presence: true
   belongs_to :user
   has_many :tags
   has_many :comments
   has_many :likes, dependent: :destroy
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
   before_action :authorize, only: [:new, :edit, :destroy]

   def index 
   @gossips = Gossip.all.reorder(id: :asc, title: :asc, content: :asc)

   puts "$" * 60
   puts "Voici le nombre de potins dans la base : #{@gossips.length}"
   puts "$" * 60
   end

   def show 
      @gossip = Gossip.find(params[:id])
      @comments = Comment.where('gossip_id': @gossip.id)
   end
   
  def new
   @new_gossip = Gossip.new 
  end

  def edit 
   @gossip = Gossip.find(params[:id])
  end

  def create 
   @gossip = Gossip.new("title" => params[:title],
                        "content" => params[:content],
                         user: current_user)
                        

   if @gossip.save 
      flash[:success] = "Le potin à bien été crée" #Specifying a message when it succeeds
      redirect_to gossips_path
   else
      render 'new'
   end
  end


 def update
   @gossip = Gossip.find(params[:id]) 
   gossip_params = params.require(:gossip).permit(:title, :content)
   if @gossip.update(gossip_params)
   redirect_to action: "show", notice: 'Success', :id => @gossip.id
   else 
   render :action => 'edit'
   end   
  end

  def destroy
   @gossip = Gossip.find(params[:id])
      @gossip.destroy
      redirect_to gossips_path
  end

end

app/views/gossips/edit.html.erb
<h1>Editer un Gossip</h1>

<div class="form-container">
<%= form_for @gossip do |f| %>
  <div class=" form-group">
     <label>Titre du Gossip</label>
     <%= f.text_field :title, class: 'form-control'%>
  </div>
  <div class=" form-group">
     <label>Contenu du Gossip</label>
     <%= f.text_area :content, class: 'form-control'%>
  </div>  
  <div class="form-group">
  <button type="submit" class= "btn btn-primary"> Modifier le gossip</button>
  </div>

 <% end %> 
 </div> 

app/views/gossips/index.html.erb
<div class="jumbotron-hero">
  <div class="container text-center" >
    <h1 class="display-4 pt-5 font-weight-bold text-dark">THE GOSSIP PROJECT</h1>
    <p class="lead pt-5 text-dark ">Join our community and share your gossips</p>
  </div>
</div>


<div class= "container d-flex justify-content-around">
   <div class= "row">
    <% @gossips.each do |gos| %>
         <div class= "col-4 col-sm-4 col-md-4 col-lg-4 mt-5 text-center" >
            <div class="card" style="width: 18rem">
            <img class="card-img-top" src="https://source.unsplash.com/200x200/?portrait?sig=<%=rand(1..50)%>" 
                alt="Card image cap" class="rounded-circle img-fluid">
               <div class="card-body">
                  <h5 class="card-title"> <%= gos.user.first_name %> </h5>  
                     <p class ="card-title">  <%= gos.title %> </p>
                     <%= link_to "Clique sur ce lien pour voir le potin au dessus", gossip_path(gos.id), class: 'btn btn-primary' %>  
                    <p class="card-title"><%= gos.likes.count %> <%= (gos.likes.count) == 1 ? 'Like' : 'Likes'%></p>
               </div>   
            </div>      
         </div>   
         <% end %>
    </div>
</div>

app/views/gossips/new.html.erb
<h1> Créer un potin ! </h1>
<p>Rentre les infos de ton potin grâce au formulaire ci dessous</p>


<% if !@gossip.nil? && @gossip.errors.any? %>
<div class="alert alert-danger" role="alert">
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>  
<% end %>
<div class="form-container"> 
<%= form_tag url_for(action: 'create'), method: "post" do %>

   <%= label_tag 'Titre' %>
   <%= text_field_tag 'title', (@gossip.title if !@gossip.nil?) %>
   <br /> <br />

   <%= label_tag 'Content' %>
      <%= text_area_tag 'content',(@gossip.content if !@gossip.nil?)  %>
      <br /> <br />

      <%= submit_tag "Enregistrer ce potin" %>

    <% end %>
</div>    

app/views/gossips/show.html.erb
<div class="card">
 <div class="card-header">
 <h1 class="text-center"> <%= @gossip.title %></h1>
 <h5 class="text-center">Voici la page du potin<%= @gossip.id %></h5>
 </div>
  <div class="container d-flex flex-column align-items-center mt-5">
  <div>
  <img src="https://source.unsplash.com/200x200/?portrait?sig=<%=rand(1..50)%>" 
                     alt="avatar" class="rounded-circle img-fluid" style="width: 150px;"> 
    <h1 class="card-title"> <%= @gossip.user.first_name %></h1>
  </div>  
   <div class="card-body">
    <p>Le content est : <%= @gossip.content %></p>
    <p>Le date de création est : <%= @gossip.created_at %></p>
    <p>La ville est : <%= @gossip.user.city.name %></p>
   </div> 
  </div>
    <p><%= @gossip.likes.count %> <%= (@gossip.likes.count) == 1 ? 'Like' : 'Likes'%></p>
    <div class="container d-flex mt-5">
      <button type="button" class="btn btn-outline-primary btn-sm w-25 p-3 me-2"><%= link_to "Author's Profile", user_path(@gossip.user.id) %></button>
      <% if current_user %>
      <button type="button" class="btn btn-outline-primary btn-sm w-25 p-3 me-2"><a href="<%=  gossip_likes_path(@gossip)%>" data-method="POST"> Liker</a></button>
      <% else %>
      <%end%>
      <% pre_like = @gossip.likes.find { |like| like.user == current_user} %>
      <% if pre_like %>
      <button type="button" class="btn btn-outline-primary btn-sm w-25 p-3 me-2"><a href="<%= gossip_like_path(@gossip, pre_like)%>" data-method="DELETE"> Supprimer </a></button> 
      <% else %>
      <% end %>

      <% if current_user == @gossip.user %>
      <button type="button" class="btn btn-outline-primary btn-sm w-25 p-3 me-2"><%= link_to "Modifier", edit_gossip_path(@gossip.id) %></button>
      <button type="button" class="btn btn-outline-primary btn-sm w-25 p-3 me-2"><%= link_to "Commenter", new_gossip_comment_path(@gossip.id) %></button> 
      <button type="button" class="btn btn-outline-primary btn-sm w-25 p-3 me-2"><a href="<%= gossip_path(@gossip.id) %>" data-method="DELETE"> Supprimer </a></button> 
    <% else %>
    <% end %>
    </div>
  </div>

  

<div class="comments"> 
<h1> Commentaires {<%= @comments.length%>} </h1>

<% @comments.each do |comment|%>
  <div class="comment">
  <img src="https://source.unsplash.com/200x200/?portrait?sig=<%=rand(1..50)%>" 
                alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
    <div>            
    <h2> <%= comment.user.first_name %> </h2>
    <h3> <%= comment.content %> </h3>
    </div>
    
    <button type="button" class="btn btn-outline-primary btn-sm w-25 p-3 me-2"><%= link_to "Edit le commentaire", edit_gossip_comment_path(@gossip, comment.id) %></button> 
    <button type="button" class="btn btn-outline-primary btn-sm w-25 p-3 me-2"><a href="<%= gossip_comment_path(@gossip, comment.id) %>" data-method="DELETE"> Supprimer </a></button> 
     
  </div>
  
 <% end %>
</div> 


<a href=""></a>