config/routes.rb
Rails.application.routes.draw do
  
  get '/', to: 'index#home'
  
  resources :gossips
  
  resources :users 
  
  resources :cities
  
  resources :gossips do 
    resources :comments
  end

  resources :gossips do 
    resources :likes
  end


  get '/login'     => 'sessions#new'
	
	# create (post) action for when log in form is submitted:
	post '/login'    => 'sessions#create'
	
	# delete action to log out:
	delete '/logout' => 'sessions#destroy'  

    get 'welcome/:first_name', to: 'welcome#show'
    #Route contact
    get '/contact', to: 'index#contact'
  
    #Route team
    get '/team', to: 'index#team'
  
  
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet"  href="../../app/assets/stylesheets/application.css">
    <link rel="stylesheet"  href="../../app/assets/stylesheets/form.css">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-info">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/contact">Contact </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/team">Team</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/gossips">Gossip</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/gossips/new">Création de Potins</a>
      </li>
    </ul>

  </div>
  <% if current_user %>
  <!-- current_user will return true if a user is logged in -->
  <%= "Logged in as #{current_user.first_name}" %> <%= link_to 'Log Out', logout_path, method: :delete %>
<% else %>
  <!-- not logged in -->
   <%= link_to 'Log In', login_path %> or <%= link_to 'Sign Up', new_user_path %>
<% end %>

<%# ----- end of added lines ----- %>

<% if notice %>
  <%= notice %>
<% end %>

<% if alert %>
  <%= alert %>
<% end %>
</nav>
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>
	
   
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>